# Nome: Alberto Rodrigues Ferreira
# Matrícula: 391278

In [0]:
import tensorflow as tf
import numpy as np
import pandas as pd
import seaborn as sea
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.utils import resample

In [440]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
dados=pd.read_csv('gdrive/My Drive/DadosDeCancer.csv')

In [442]:
dados.head()

class    age menopause tumor-size inv-nodes node-caps  \
0  no-recurrence-events  30-39   premeno      30-34       0-2        no   
1  no-recurrence-events  40-49   premeno      20-24       0-2        no   
2  no-recurrence-events  40-49   premeno      20-24       0-2        no   
3  no-recurrence-events  60-69      ge40      15-19       0-2        no   
4  no-recurrence-events  40-49   premeno        0-4       0-2        no   

   deg-malig breast irradiat  
0          3   left       no  
1          2  right       no  
2          2   left       no  
3          2  right       no  
4          2  right       no

In [0]:
dados2=dados

Função para transformar as variáveis categóricas em numéricas.

In [0]:
#Essa função irá fazer parte da matriz X para cada variável categórica, ela irá percorrer todas as observações dessa variável
# e dizer 1 se ela for de um tipo específico e 0 se não for, e faz por coluna.
def CaselaDeReferencia(x):
    #Criando matriz para cada variável categórica com o número de linhas igual ao número de observações e o número de colunas
    #igual ao número de categorias únicas - 1.
    matriz=np.empty(shape=(len(x),len(np.unique(x))-1),dtype=int)
    #Andando pelas indices das colunas.
    for i in range(matriz.shape[1]):
        #Andando pelo indice das linhas (observações).
        for j in range(len(x)):
            if x[j]==np.unique(x)[1:][i]:
            #Se for o tipo específico dos tipos da variável a linha vai ser 1 ou 0 caso contrário.
                matriz[j,i]=1
            else:
                matriz[j,i]=0
    return matriz

In [445]:
dados2.columns

Index(['class', 'age', 'menopause', 'tumor-size', 'inv-nodes', 'node-caps',
       'deg-malig', 'breast', 'irradiat'],
      dtype='object')

Matriz X que irá compor as variáveis escolhidas e uma coluna de uns representando o intercepto, e também padronizei a variável numérica.

In [446]:
X=(np.column_stack((np.ones(dados2.shape[0]),CaselaDeReferencia(dados2["age"]),CaselaDeReferencia(dados2["menopause"]),CaselaDeReferencia(dados2["tumor-size"])
                  ,CaselaDeReferencia(dados2["inv-nodes"]),CaselaDeReferencia(dados2["node-caps"]),CaselaDeReferencia(dados2["breast"])
                  ,CaselaDeReferencia(dados2["irradiat"]),dados2["deg-malig"])))

X[:,-1]=scale(X[:,-1])
X[:,-1]

array([ 1.29056424, -0.0664261 , -0.0664261 , -0.0664261 , -0.0664261 ,
       -0.0664261 , -0.0664261 , -1.42341644, -0.0664261 , -0.0664261 ,
        1.29056424, -0.0664261 , -1.42341644,  1.29056424,  1.29056424,
       -1.42341644, -0.0664261 ,  1.29056424,  1.29056424, -1.42341644,
       -0.0664261 , -0.0664261 , -0.0664261 , -0.0664261 , -0.0664261 ,
       -0.0664261 , -1.42341644,  1.29056424, -0.0664261 , -0.0664261 ,
        1.29056424, -0.0664261 ,  1.29056424, -1.42341644, -1.42341644,
       -0.0664261 , -0.0664261 , -1.42341644, -0.0664261 , -1.42341644,
       -1.42341644, -0.0664261 , -1.42341644, -0.0664261 , -1.42341644,
       -1.42341644, -0.0664261 , -1.42341644, -1.42341644, -1.42341644,
       -0.0664261 , -0.0664261 , -1.42341644,  1.29056424, -1.42341644,
       -1.42341644, -1.42341644, -0.0664261 , -1.42341644, -1.42341644,
       -0.0664261 , -1.42341644, -1.42341644, -0.0664261 , -1.42341644,
       -1.42341644, -1.42341644,  1.29056424,  1.29056424, -0.06

In [447]:
Y=dados2["class"].values
Y=np.array([1 if i=="no-recurrence-events" else 0 for i in dados["class"]])
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
xtreino,xteste,ytreino,yteste=train_test_split(X,Y,test_size=0.3,random_state=7)
ytreino=ytreino.reshape(-1,1)
yteste=yteste.reshape(-1,1)

In [0]:
#Hiperparâmetros do modelo.
Taxa=0.05
Epocas=20000
Passos=2000

In [0]:
x= tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
#Pesos com inicializações aleatórias.
Beta = tf.Variable(np.random.randn(xtreino.shape[1],1),dtype=tf.float32)

In [0]:
#Modelo que preve a probabilidade de ocorrência de sucesso nesse caso é a ocorrência de cancêr não-recorrente.
Modelo = 1/(1+tf.math.exp(-tf.matmul(x,Beta)))
 
#Função Custo
Custo = (tf.reduce_sum(-y*(tf.math.log(Modelo))-(1-y)*tf.math.log(1-Modelo)) / (2*dados.shape[0]))
 
#Otimização com Gradiente Descendente
Treino = tf.train.GradientDescentOptimizer(Taxa).minimize(Custo)

Aprendizado com o gradiente descente que no final dá todos os parâmetros do modelo convergindo.

In [452]:
init=tf.global_variables_initializer()
# Iniciando a sessão
with tf.Session() as sess:
    # Iniciando as variáveis
    sess.run(init)
    # Treinamento do modelo
    for i in range(Epocas):
        sess.run(Treino, feed_dict={x: xtreino, y: ytreino})
        if (i+1) % Passos == 0:
            c = sess.run(Custo, feed_dict={x: xtreino, y: ytreino})
            print(i+1,"\n", c,"\n" ,sess.run(Beta))
    # Imprimindo os parâmetros finais do modelo
    custo_treinamento = sess.run(Custo, feed_dict={x: xtreino, y: ytreino})
    print("Custo Final de Treinamento:", custo_treinamento, "\n Parâmetros:\n", sess.run(Beta))
    # Testando o modelo
    custo_teste = sess.run(tf.reduce_sum(tf.square(Modelo - y)) / (2 * xteste.shape[0]), feed_dict={x: xteste, y: yteste})     
    print("Custo Final em Teste:", custo_teste)
    ypredito=sess.run(1/(1+tf.math.exp(-tf.matmul(xteste.astype("float32"),Beta))))

2000 
 0.1918206 
 [[ 0.38847053]
 [-1.4680929 ]
 [ 0.45065674]
 [ 0.54654205]
 [ 0.06795641]
 [ 0.0676682 ]
 [ 0.12966648]
 [ 0.03307079]
 [ 0.6616117 ]
 [ 0.15204675]
 [-0.12966873]
 [-0.21044265]
 [-0.34537962]
 [ 0.8096144 ]
 [ 0.5813156 ]
 [ 0.56700104]
 [ 0.4546299 ]
 [-0.9546574 ]
 [ 1.0342262 ]
 [-1.6056944 ]
 [ 1.1275625 ]
 [ 0.20400167]
 [-0.13649954]
 [-1.2299215 ]
 [ 0.6464412 ]
 [-0.69420844]
 [ 0.17218566]
 [ 0.35964048]
 [-0.48339462]]
4000 
 0.18302286 
 [[ 0.48846617]
 [-1.1082414 ]
 [ 0.25512332]
 [ 0.2647777 ]
 [ 0.27069396]
 [ 0.06364974]
 [-0.05525071]
 [ 0.06203619]
 [ 0.8615677 ]
 [ 0.08402461]
 [-0.15491767]
 [-0.35558203]
 [-0.30257764]
 [ 0.6867771 ]
 [ 0.63062805]
 [ 0.6684318 ]
 [ 0.48048815]
 [-0.9400211 ]
 [ 0.9408382 ]
 [-1.4920292 ]
 [ 1.0154645 ]
 [-0.01153762]
 [-0.03826639]
 [-1.0998416 ]
 [ 0.61434263]
 [-0.37653628]
 [ 0.25638914]
 [-0.05481663]
 [-0.4448859 ]]
6000 
 0.1805925 
 [[ 0.53465945]
 [-0.9862596 ]
 [ 0.21792391]
 [ 0.17564543]
 [ 0.30530

Comparação entre o valor predito e o valor real, usando como ponto de corte p=0.5.




In [453]:
np.column_stack((np.round(ypredito),yteste))

array([[1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.

In [454]:
#Matriz de confusão
confusion_matrix(yteste,np.round(ypredito))

array([[ 6, 22],
       [ 5, 53]])

In [455]:
#Métricas de acurácia
print(classification_report(yteste,np.round(ypredito)))

              precision    recall  f1-score   support

           0       0.55      0.21      0.31        28
           1       0.71      0.91      0.80        58

   micro avg       0.69      0.69      0.69        86
   macro avg       0.63      0.56      0.55        86
weighted avg       0.65      0.69      0.64        86

